### ISSUE TITLE
Convert Content Editor Overview

### ISSUE THREAD

**Issue by jsmcintyre25** [wptrainingteam/content-editor-overview#1]
Convert Lesson Plan to GitHub

- [x]  copy and paste from Make site
- [x]  clean up the Markdown
- [x]  download the old images
- [x]  upload the images into GitHub
- [x]  swap out the image links

**Comment by JulieKuehl** [comment]
https://make.wordpress.org/training/handbook/user-lessons/content-editor-overview/

**Comment by JulieKuehl** [comment]
images were unrecoverable
